# encoding: utf-8
require "protocop/fields/frame"
require "protocop/fields/bit32"
require "protocop/fields/bit64"
require "protocop/fields/length_delimited"
require "protocop/fields/varint"
require "protocop/fields/boolean"
require "protocop/fields/double"
require "protocop/fields/fixed64"
require "protocop/fields/int32"
require "protocop/fields/int64"
require "protocop/fields/sfixed64"
require "protocop/fields/sint32"
require "protocop/fields/sint64"
require "protocop/fields/uint32"
require "protocop/fields/uint64"
require "protocop/fields/string"
